version: "3"

services:
  catalog:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: catalog
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: catalog-rabbitmq
    hostname: rabbitmq
    ports:
      - 15671:15671
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./rabbitmqdata:/var/lb/rabbitmq/mnesia

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: catalog-elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - ./.docker/elasticdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: catalog-kibana
    ports:
      - 5601:5601
