version: '3'

services:
  catalog:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: catalog
    ports:
      - 3000:3000
    env_file: ./.env.dev
    volumes:
      - .:/home/node/app
